### ISSUE TITLE
DynamoDb: Parsing of Boolean type throws Exception

### ISSUE THREAD

**Issue by janlisse** [dwhjames/aws-wrap#42]
When trying to parse a Boolean value from DynamoDb into a Scala Boolean using the implicit conversions from the package object this throws an Exception:

```
Caused by: java.lang.IllegalArgumentException: For input string: "null"
        at scala.collection.immutable.StringLike$class.parseBoolean(StringLike.scala:293) ~[scala-library-2.11.7.jar:na]
        at scala.collection.immutable.StringLike$class.toBoolean(StringLike.scala:260) ~[scala-library-2.11.7.jar:na]
        at scala.collection.immutable.StringOps.toBoolean(StringOps.scala:30) ~[scala-library-2.11.7.jar:na]
        at com.github.dwhjames.awswrap.dynamodb.package$$anonfun$39$$anonfun$apply$7.apply$mcZ$sp(package.scala:266) ~[aws-wrap_2.11-0.8.0.jar:0.8.0]
        at com.github.dwhjames.awswrap.dynamodb.package$$anonfun$39$$anonfun$apply$7.apply(package.scala:266) ~[aws-wrap_2.11-0.8.0.jar:0.8.0]
        at com.github.dwhjames.awswrap.dynamodb.package$$anonfun$39$$anonfun$apply$7.apply(package.scala:266) ~[aws-wrap_2.11-0.8.0.jar:0.8.0]
        at com.github.dwhjames.awswrap.dynamodb.package$.com$github$dwhjames$awswrap$dynamodb$package$$catchAndRethrowConversion(package.scala:221) ~[aws-wrap_2.11-0.8.0.jar:0.8.0]
        at com.github.dwhjames.awswrap.dynamodb.package$$anonfun$39.apply(package.scala:266) ~[aws-wrap_2.11-0.8.0.jar:0.8.0]
        at com.github.dwhjames.awswrap.dynamodb.package$$anonfun$39.apply(package.scala:266) ~[aws-wrap_2.11-0.8.0.jar:0.8.0]
```

**Comment by mingchuno** [comment]
@janlisse 
I have forked this repo and published it under version 0.9.0
https://github.com/mingchuno/aws-wrap

Can you please check if you still have any problems? If yes, please submit an issue there
